# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
	lock_cmd = hyprlock
	before_sleep_cmd = hyprlock
	# after_sleep_cmd =
}

# Lower screen brightness
listener {
	timeout = 240 # 4 min
	on-timeout = brightnessctl -s set 25%- -n 1% # Don't turn off
	on-resume = brightnessctl -r
}

# Turn off screen
listener {
	timeout = 480 # 8 min
	# Do not save brightness before this, the screen dimming
	# would be overwritten
	on-timeout = brightnessctl set 0
	on-resume = brightnessctl -r
}

# Show lockscreen
listener {
	timeout = 720 # 12 min
	on-timeout = hyprlock
}

# Suspend pc
#listener {
#	timeout = 1800 # after 30 min
#	on-timeout = systemctl suspend
#}
