# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
	# Don't wait for image to load, fallback to bg color
	# immediate_render = true
}

background {
	monitor =
	path = ~/Bilder/Nature-Hills-Wallpaper.jpg
	color = rgb(255, 206, 0)
}

input-field {
	monitor =
	size = 20%, 5%

	outline_thickness = 5
	
	inner_color = rgb(80, 92, 26)
	outer_color = rgb(251, 150, 18)
	check_color = rgb(252, 250, 147)
	fail_color = rgb(218, 10, 8)

	font_color = rgb(251, 252, 62)
}

# Day/months
label {
	monitor =
	# Dayname Day Month
	text = cmd[update:10000] echo "$(date "+%A %d %B")"

	font_size = 50
	font_family = JetBrainsMono Nerd Font

	#position = 0, 175
	position = 0, 20%
	halign = center
	valign = center
}

# Time
label {
	monitor =
	# Hour Minute Second
	text = cmd[update:500] echo "$(date "+%H:%M:%S")"

	font_size = 35
	font_family = JetBrainsMono Nerd Font

	#position = 0, 80
	position = 0, 10%
	halign = center
	valign = center
}

# Battery
label {
	monitor =
	text = cmd[update:5000] ~/.config/scripts/battery-fancy.sh
	font_size = 25
	font_family = JetBrainsMono Nerd Font Propo
	text_align = right

	position = -10,0
	halign = right
	valign = bottom
}
